language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo fmt -- --check --edition 2018
  - cargo build 
  - cargo test

notifications:
  email:
    on_success: never
